# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build
      run: go build -o automator-api/main automator-api/main.go

    - name: Prepare SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        scp -o StrictHostKeyChecking=no automator-api/main ubuntu@REDACTED_IP:/home/ubuntu/automator-api/main
        ssh -o StrictHostKeyChecking=no ubuntu@REDACTED_IP << 'EOF'
          pkill -f main || true
          mv /home/ubuntu/automator-api/main /home/ubuntu/automator-api/main-old || true
          chmod +x /home/ubuntu/automator-api/main
          nohup /home/ubuntu/automator-api/main > /dev/null 2>&1 &
        EOF

    - name: Clean up
      run: rm -f automator-api/main
